query anime($id: Int) {
  Media(id: $id, type: ANIME) {
    id
    title {
      english
      romaji
    }
    description
    coverImage {
      extraLarge
    }
    averageScore
    characters(perPage: 6, sort: [ROLE, RELEVANCE, ID]) {
      nodes {
        id
        name {
          full
        }
        image {
          large
        }
        siteUrl
      }
    }
    rankings {
      id
      rank
      context
    }
    startDate {
      year
      month
      day
    }
    endDate {
      year
      month
      day
    }
    studios(isMain: true) {
      nodes {
        id
        name
      }
    }
    genres
  }
}
